-- Import Buildings Data (List Gedung BM SITACQ IOH)
-- Data from Screenshot 1

-- Jakarta Zone 1 Buildings
INSERT INTO buildings (building_name, address, city, zone, country) VALUES
('Ariha Graha', 'Jl. Jend. Gatot Subroto Kav. 32-34, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Pacific Place', 'SCBD Lot 3-5, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara Astra', 'Jl. Jend. Sudirman Kav. 5-6, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Jakarta Stock Exchange (BEJ)', 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Soekarno Hatta Airport', 'Soekarno Hatta International Airport, Tangerang', 'Tangerang', 'Zone 1', 'Indonesia'),
('Angkasa Pura I', 'Jl. Angkasa Blok B-15, Kemayoran, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Jamasostek Building', 'Jl. Jend. Gatot Subroto Kav. 38, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Wisma Aldiron Dirgantara', 'Jl. Gatot Subroto Kav. 72, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Cibis Nine', 'Jl. TB Simatupang No. 2, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Millennium Centennial Center', 'Jl. Jend. Sudirman Kav. 25, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Wisma Barito Pacific', 'Jl. S. Parman Kav. 60, Jakarta Barat', 'Jakarta', 'Zone 1', 'Indonesia'),
('The Energy Building', 'SCBD Lot 11A, Jl. Jend. Sudirman, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Cyber 1 Building', 'Jl. Kuningan Barat I No. 26, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Cyber 2 Tower', 'Jl. HR Rasuna Said Blok X-5 Kav. 13, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara BCA', 'Grand Indonesia, Jl. MH Thamrin No. 1, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Plaza BII', 'Jl. MH Thamrin No. 51, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Wisma BSG', 'Jl. Abdul Muis No. 40, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara Caraka', 'Jl. Gatot Subroto Kav. 18, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Artha Graha Building', 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('The Plaza Office Tower', 'Jl. MH Thamrin Kav. 28-30, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Sampoerna Strategic Square', 'Jl. Jend. Sudirman Kav. 45-46, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Senayan City', 'Jl. Asia Afrika Lot 19, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara Rajawali', 'Jl. DR Ide Anak Agung Gde Agung Kav E.3.2 No.1-2, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Wisma Mulia', 'Jl. Gatot Subroto Kav. 42, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Equity Tower', 'SCBD Lot 9, Jl. Jend. Sudirman, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Sequis Tower', 'Jl. Jend. Sudirman Kav. 71, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Indonesia Stock Exchange Tower 1', 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Indonesia Stock Exchange Tower 2', 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Telkom Landmark Tower', 'Jl. Gatot Subroto Kav. 52, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Gedung Cyber', 'Jl. Kuningan Barat No. 8, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Grha Niaga', 'Jl. Jend. Sudirman Kav. 58, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Wisma 46', 'Jl. Jend. Sudirman Kav. 1, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Plaza Indonesia', 'Jl. MH Thamrin Kav. 28-30, Jakarta Pusat', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara Imperium', 'Jl. HR Rasuna Said Kav. 1, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Lippo Kuningan', 'Jl. HR Rasuna Said Kav. B-12, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Menara Standard Chartered', 'Jl. Prof. DR Satrio Kav. 164, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('Gedung Bursa Efek Indonesia', 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('World Trade Center 1', 'Jl. Jend. Sudirman Kav. 29-31, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('World Trade Center 2', 'Jl. Jend. Sudirman Kav. 29-31, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia'),
('World Trade Center 3', 'Jl. Jend. Sudirman Kav. 29-31, Jakarta Selatan', 'Jakarta', 'Zone 1', 'Indonesia')
ON CONFLICT DO NOTHING;
